<?php

namespace App\Extensions;


use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\LiteralField;
use SilverStripe\ORM\DataExtension;
use SilverStripe\SiteConfig\SiteConfig;
use SilverStripe\Assets\Image;

class SiteConfigExtension extends DataExtension
{
//   public function requireDefaultRecords()
//   {
//       parent::requireDefaultRecords(); // TODO: Change the autogenerated stub
//       SiteConfig::get()->first()->Title="Gecco";
//       SiteConfig::get()->first()->Tagline="CLAD Online";
//   }

    /**
     * Has_one relationship
     * @var array
     */
    private static $has_one = [
        'Logo' => Image::class
    ];
    private static $owns = [
        'Logo'
    ];

//    /**
//     * Update Fields
//     * @param FieldList $fields
//     * @return FieldList
//     */
//    public function updateCMSFields(FieldList $fields)
//    {
//        $owner = $this->owner;
//        $fields->addFieldsToTab(
//            'Root.Main',
//            [
//                UploadField::create(
//                    'SiteLogo',
//                    'Site Logo'
//                )->setDescription('This is the full sized logo')
//                    ->setFolderName('Settings/Logos'),
//                UploadField::create(
//                    'SiteLogoSmall',
//                    'Site Logo Small'
//                )->setDescription('Smaller, <em>"icon"</em> sized logo')
//                    ->setFolderName('Settings/Logos')
//
//            ]
//        );
//
//
//        return $fields;
//    }


    public function getCMSFields() {
        $fields = parent::getCMSFields();
        $fields->addFieldToTab("Root.Main", UploadField::create('Logo'));
        return $fields;
    }


    public function requireDefaultRecords()
    {
        parent::requireDefaultRecords(); // TODO: Change the autogenerated stub
        $sc = SiteConfig::get()->first();
        $sc->Title="Gecco";
        $sc->Tagline="CLAD Online";
        $sc->write();
    }



}

//   public function updateCMSFields(FieldList $fields)
//   {
//       parent::updateCMSFields($fields); // TODO: Change the autogenerated stub
//       $fields->addFieldToTab("Root.Main",
//                                LiteralField::create("","Hello World"));
//   }
//}
