<?php

namespace App\Forms;

use Page;


class HomePage extends Page
    {
        public function requireDefaultRecords()
        {
            parent::requireDefaultRecords(); // TODO: Change the autogenerated stub
            if (!HomePage::get()->first()) {
                $Page = new HomePage();
                $Page->Title = 'Home';
                $Page->write();
                $Page->publishRecursive();
                $Page->CanEditType = "Home Page";
                DB::alteration_message('Added Home page', 'created');
            }
        }


    }

