<?php

namespace App\Forms;


use Page;
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\HTMLEditor\HTMLEditorField;
use SilverStripe\Forms\TextField;
use SilverStripe\ORM\DataObject;
use SilverStripe\ORM\DB;

class SignupPage extends Page
{

//  private static $db =[
//    'AfterRegistrationTitle'=> 'Varchar(255)',
//      'AfterRegistrationContent'=> 'HTMLText'
//  ];
//
//
//
//  /**
//   * CMS Fields
//   * @return FieldList
//  */
//  public function getCMSFields()
//  {
//      $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub
//
//
//      $fields= FieldList::create(
//          TextField::create('Title'));
//      return $fields;
//  }

//  private static $defaults = [
//      'AfterRegistrationTitle' => 'Registration Successful',
//      'AfterRegistrationContent' => '<p> Thank you for registering.</p>'
//  ];

  public function requireDefaultRecords()
  {
      parent::requireDefaultRecords(); // TODO: Change the autogenerated stub
      if(!SignupPage::get()->first()){
          $Page = new SignupPage();
          $Page->Title = 'Sign Up';
          $Page->write();
          $Page->publishRecursive();
          DB::alteration_message('Added sign up page', 'created');
      }
  }



}
